steps:
# Install dependencies
- name: "python:3.8"
  entrypoint: "pip"
  args: ["install", "--upgrade", "-r", "requirements.txt", "-t", "."]

# Deploy to Cloud Function
- name: "gcr.io/cloud-builders/gcloud"
  entrypoint: "bash"
  args:
  - "-c"
  - |
    gcloud auth activate-service-account --key-file=noble-amp-384713-6597fe149049.json
    gcloud functions deploy nn-test --runtime python310 --trigger-http --source=.
  secretEnv: ['SERVICE_ACCOUNT_KEY']

secrets:
- kmsKeyName: projects/your-project/locations/global/keyRings/your-key-ring/cryptoKeys/your-key
  secretEnv:
    SERVICE_ACCOUNT_KEY: "ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAibm9ibGUtYW1w
LTM4NDcxMyIsCiAgInByaXZhdGVfa2V5X2lkIjogIjY1OTdmZTE0OTA0OTdkMDdhMjZiYzczYWI1
ZWQ1NWExNGRlYjk5OTQiLAogICJwcml2YXRlX2tleSI6ICItLS0tLUJFR0lOIFBSSVZBVEUgS0VZ
LS0tLS1cbk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFR
Q3lScURYZjR5TFRRRmVcbm5WYWpTOUY0UlFkTTdBMFFJdHNEMjlEQXlFR3AyekdaTnlxUjk0U0hx
eHhaK0JGbUNRWHdMRXF5OXZRc3psNkVcbm5FN1B2ZWs1OFRKa1VVQ3RXR3ZKR3AzVW1NNkNpUXNO
L3RuUm9DblJaMm12MXV0TTJVU3h0Zms2MWtIbGJRZGVcbjVXSGFkSXE2WFczL2ZHdVVHMVZSRVNy
Y2FvOHk1OU1VTmhNNHlmWUU5RXdBaWU0Z2E2Y0Exd0hJOG1nUFF1eE5cbng5OU5XZTR5SmcyTERI
RVVvWDlsbm9LWjlPM1ZSVkxQN1R4Q1dNWUpvT1RDL2ZKMzhNblZRbVAvV3M1ZFJTMHZcblhDN2dB
R3VlL0doYUJ3dUlQZ1k2V1dSYzZhbjMxWGRyUkk2OEpPQmEwWis5OTNPZXpob0JDbVM2VWFibTAr
U0dcbi8wbmtQbjQ5QWdNQkFBRUNnZ0VBSlErbVFjNkFFUGg3KzZlaFduYTVUL09udWgvTGNtcVFs
ZHVGYVFKb2xpOWRcbmZ3RFhMbnVpbDFLazVQWTdaYmNqL3lNeUQwVGtDNG1HWURLZmRyUUFEMzNi
TUR3dEFpeGkwZTZnMTVEQnc2VEtcblFjbFVqbTNwcTZFQU9XQW9UL1JPQWRTM0FIcUl2ZkY5eWda
TklxMCtKdEtqK3F3cXNDSkRpUVFVNFRnYzEyTzlcbkZXeGpDTVNMNVRYcDl2Z21EY1Y5YkJrSk80
aHhZblE3OGRVcVdwNHNucXdFK2MrdzYrY2x2WXBUbFBPN3VySFZcbjQ3VWpTRXdnZmQ1YUFzMnE3
OSt1dWprRXBMVFA2WHVpK1pNSlhJK0VuTUlxWnVCckJZMDhmSW1ZRXZjbWdSYjRcbk5zRU92L2xB
K1lIeWtHQ0xraUVTN3ZUYTJqWkYzUlRWeEJDWElIdDMyUUtCZ1FEMUh1ZFhzc0EwNURmckJpbWJc
blVTOE9qb3lMcmlVQUF5WVBRZU5sSS8ySWFCQ01XRGdSa3M0WGlFSjdkaVhzTTAvV3BDOEc4OUx1
STNCNlNEbTRcbjllUzg4aUF0OXVjNXp3MjhtQ1N4bWt4YzlPbWdkMEhiN29XaUVRUkR5MU8vemdW
L2paMkptdVRwWW1nOTJVYi9cbmR4WWpFU2M4UCtWOURIQ0w0SUxGT3Zqb0JRS0JnUUM2TURsbTVT
V2hpK0ZTU0I5Z0ZOdU0vem5xUzlUbWg1UnJcbjdlTXZ3d2VvMXZ4Rmg0RHlHSUxZY2tBWlVzbUM5
enRHT1ZGNjNTb1FFQW1XcjFRSGtwNGMyZVRMTHh1c2MyNHpcbkRkanMwQSt1LzhkaUFEVk5vS081
Nk1jalo2V1JQcEkydTZrdVNmRzg5ZXhtTWVCcnd4ck52Qks0SWFNbGVSbFhcbkJ1SEdLRDBxMlFL
QmdRQ2NyaU5NQUZzeHM4czJkRnIyQjUrZm0yaWxCQ3hzWkpiWVc5SmhYTzc3V1NGeXhCVWFcbnpv
N2pwZHB4Rm1WSkpNZGN1TmZDaHVvR0JDc3FUcTV1MXVaZURCcWJwdDNJS3R4cDk0cEU2QTcxd0Ny
eHdpa2Jcbnpzd21ldUFTQVk3SDVJWEpNWmxJVXZVTlpUU2lqQmNBeG5zazhScjJQUldRcC9uc3Z4
WjN3YWxHalFLQmdIK0NcbjFWMGRvK2IrR0dNMGw2QkN5SlhJbVk1WFBzaGVwQXhDa0N1K29ybEQr
dU5YU0wwRWdsL2Y1dnd3MFdjTEVLSW9cblVTQVc1VjY0elFoUXJQaSt0ZUJHYmNXbFRvdU5SalJh
MEd4bWxjY2d6eGpUMGEySFRYbmQ3THZYbVBGZTY5M21cbktaaFU5ZVNXZTc4RmU0L3h2NktVb2pG
T2dDQUN6cExtV0t0UUZZd0pBb0dBQW84WnlNeC9YYVpSNXVwaG5MaUZcbndYSGdwZDB1TU55dzFL
MWxzR0pQY2sveThqazQ1S21JWGh5TXBITTBxSzJRZDR4VkptMVh1b3BWY1kvSDY4ZytcblBLSmFQ
VWpNTzJSdjh3T3RpdGYzdDhqcTgvb1pjZ3F6QlF6azR5clRaby9kQ2hYQThLd3ZLallxUVVpUFlB
VS9cbmNTM0dhemRTcDl5dzFWaGUxZTRhL2VzPVxuLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLVxu
IiwKICAiY2xpZW50X2VtYWlsIjogIm5uLWFjY291bnQtc2VydmljZS10ZXN0QG5vYmxlLWFtcC0z
ODQ3MTMuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJjbGllbnRfaWQiOiAiMTE0NTQ2MjMy
NDcwOTI2MTcyNjkyIiwKICAiYXV0aF91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29t
L28vb2F1dGgyL2F1dGgiLAogICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBp
cy5jb20vdG9rZW4iLAogICJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93
d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwKICAiY2xpZW50X3g1MDlfY2VydF91
cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS9u
bi1hY2NvdW50LXNlcnZpY2UtdGVzdCU0MG5vYmxlLWFtcC0zODQ3MTMuaWFtLmdzZXJ2aWNlYWNj
b3VudC5jb20iLAogICJ1bml2ZXJzZV9kb21haW4iOiAiZ29vZ2xlYXBpcy5jb20iCn0K"
