steps:
# Install dependencies
- name: "python:3.10"
  entrypoint: "pip"
  args: ["install", "--upgrade", "-r", "requirements.txt", "-t", "."]

# Deploy to Cloud Function
- name: "gcr.io/cloud-builders/gcloud"
  entrypoint: "bash"
  args:
  - "-c"
  - |
    gcloud auth activate-service-account --key-file=noble-amp-384713-6597fe149049.json
    gcloud functions deploy nn-test --runtime python310 --trigger-http --source=.
  secretEnv: ['SERVICE_ACCOUNT_KEY']

secrets:
- kmsKeyName: projects/your-project/locations/global/keyRings/your-key-ring/cryptoKeys/your-key
  secretEnv:
    SERVICE_ACCOUNT_KEY: ""
